name: C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up MinGW
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: mingw-w64-x86_64-gcc mingw-w64-x86_64-gcc-libs

    - name: Check MinGW installation
      shell: msys2 {0}
      run: |
        g++ --version
        which g++

    - name: List directory contents
      shell: cmd
      run: |
        dir
        if exist capital_cities.txt (
          echo Content of capital_cities.txt:
          type capital_cities.txt
        ) else (
          echo capital_cities.txt not found
        )

    - name: Build
      shell: msys2 {0}
      run: |
        g++ -std=c++17 -o capital_cities_game.exe capital_cities_game.cpp
        if [ $? -ne 0 ]; then
          echo "Build failed"
          exit 1
        fi

    - name: List directory contents after build
      shell: cmd
      run: dir

    - name: Test
      shell: msys2 {0}
      run: |
        echo "Running capital_cities_game.exe in non-interactive mode..."
        ./capital_cities_game.exe --non-interactive

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: capital-cities-game
        path: |
          capital_cities_game.exe
          capital_cities.txt
