name: C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up MinGW
      uses: egor-tensin/setup-mingw@v2
      with:
        platform: x64

    - name: Check MinGW installation
      run: |
        g++ --version
        where g++
      shell: cmd

    - name: List directory contents
      run: |
        dir
        if exist capital_cities.txt (
          echo Content of capital_cities.txt:
          type capital_cities.txt
        ) else (
          echo capital_cities.txt not found
        )
      shell: cmd

    - name: Build
      run: |
        g++ -std=c++17 -o capital_cities_game.exe capital_cities_game.cpp
        if %errorlevel% neq 0 exit /b %errorlevel%
      shell: cmd

    - name: List directory contents after build
      run: dir
      shell: cmd

    - name: Test
      run: |
        echo "Running capital_cities_game.exe..."
        .\capital_cities_game.exe
      shell: cmd

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: capital-cities-game
        path: |
          capital_cities_game.exe
          capital_cities.txt
